[build]
  command = "npm run build"
  # command = "apt-get update && apt-get install -y python3-dev && pip install -r requirements.txt"
  publish = "build"

[context.production]
  environment = { NODE_ENV = "production" }

[build.environment]
  MISE_SETTINGS_PYTHON_COMPILE = "false"
  PYTHON_VERSION = "3.8.0"
