[[redirects]]
  from = "/api/*"
  to = "http://172.10.7.20:8000/api/:splat"
  status = 200
[build]
  command = "apt-get update && apt-get install -y python3-dev && pip install -r requirements.txt"
  publish = "build"
